project_id = "xefypnmvsikrdxzepgqf"

[functions.resend-confirmation]
verify_jwt = true

[functions.foreman-chat]
verify_jwt = false

[functions.generate-journey-content]
verify_jwt = false

[functions.admin-import-journeys]
verify_jwt = true

[functions.generate-recovery-plan]
verify_jwt = true

[functions.send-specialist-invitation]
verify_jwt = true

[functions.test-function]
verify_jwt = false

[functions.thought-packs]
verify_jwt = false

[functions.invite-admin]
verify_jwt = true

[functions.permanently-delete-specialist]
verify_jwt = true

[functions.user-management]
verify_jwt = true

[functions.check-password-status]
verify_jwt = true

[functions.phone-redirect]
verify_jwt = false

[functions.phone-request-cleanup]
verify_jwt = false