// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xefypnmvsikrdxzepgqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZnlwbm12c2lrcmR4emVwZ3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDk3ODcsImV4cCI6MjA2NzgyNTc4N30.ezK7UD7UDoFWJBv4X2V-oiqJQj7P2XZM1Q96o4YG5ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});